name: Translations

on:
  # Trigger the workflow only on master
  push:
    branches:
      - master

jobs:
  code_style:
    if: ( github.repository == 'lutraconsulting/input' ) && (!contains(github.event.head_commit.message, 'Translate '))
    runs-on: ubuntu-latest
    env:
      QT_VERSION: '5.14.2'
    steps:

      - uses: actions/checkout@v2

      # Qt
      - name: Cache Qt
        id: cache-qt
        uses: pat-s/always-upload-cache@v2.1.5
        with:
          path: ${{ github.workspace }}/Qt
          key: ${{ runner.os }}-QtCache-v2-${{ env.QT_VERSION }}-i18n

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ env.QT_VERSION }}
          target: android
          arch: android
          dir: ${{ github.workspace }}
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Check for new translation entries
        run: |
          ./scripts/update_i18n_ts.bash ${{ github.workspace }}/Qt/${{ env.QT_VERSION }}/android

          echo "Changes in i18n entries"
          git diff app/i18n/input_en.ts | grep -E \\+\\\s+\<source\> || true

          NCHANGES=`git diff app/i18n/input_en.ts | grep -E \\+\\\s+\<source\> | wc -l`
          echo "Number of changes $NCHANGES"

          if [ "$NCHANGES" -gt "0" ]; then
            echo "Run ./scripts/update_i18n_ts.bash to fix"
            echo "Step ./scripts/release_i18n_qm.bash skipped do to this error"
            exit 1
          fi

      - name: Check if qm files are up-to-date
        run: |
          ./scripts/release_i18n_qm.bash

          echo "Unreleased translations (translated but not released)"
          git diff --name-only -- ':!*input_i18n.qrc' || true

          echo "Number of changes"
          NCHANGES=`git diff --name-only -- ':!*input_i18n.qrc' | wc -l`
          echo "Number of changes $NCHANGES"

          if [ "$NCHANGES" -gt "0" ]; then
            echo "Run ./scripts/release_i18n_qm.bash to fix"
            exit 1
          fi
